# SITE SETTINGS
title:                Extending Sweetness oOo˚o˚ a docu-drama of rainmaking
subtitle:             Art Director and Designer
email:                chloe@otherwise.cm
author:               Otherwise
description:          Benjamin Kinzer - Creative Director and Designer who loves great ideas and making them real.
baseurl:              "" # subpath if necessary, e.g. /blog/
url:                  "http://extendingsweetness.org" # base url http://url.com

# COLLECTIONS
collections:
- news

# BUILD
include:              ["_prototypes"]

# GOOGLE ANALYTICS
google_analytics:     UA-857352-1

# BUILD SETTINGS
markdown:             kramdown
permalink:            pretty
paginate:
sass:
  sass_dir:           /assets/_sass/
  compressed:         true

# PERMALINKS
permalink:            /:categories/:year/:title

# FEATURE SETS
show_related_posts:   false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# SOCIAL
show_social:          false
github_username:
twitter_username:
linkedin_username:
flattr_button:

# Post sharing icons
show_sharing:         false
share_text:           'Share this post!'
# Change to 'true' to enable individual icons
share_facebook:       false
share_twitter:        false
share_googleplus:     false
share_linkedin:       false
share_digg:           false
share_tumblr:         false
share_reddit:         false
share_stumbleupon:    false
share_hackernews:     false

# GEMS
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
